exclude: ^.venv/ # Directory exclusion
repos:

-   repo: https://github.com/psf/black
    rev: 23.1a1
    hooks:
        - id: black

-   repo: https://github.com/PyCQA/pydocstyle
    rev: 6.2.2
    hooks:
    -   id: pydocstyle

-   repo: https://github.com/PyCQA/isort
    rev: v5.11.3
    hooks:
    -   id: isort

-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args: [--max-line-length=133]

