on:
  push:
    branches:
      - "master"
env:
  PDOC_ALLOW_EXEC: 1
  TOKEN: "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"
  ACTIONS_TOKEN: ${{ secrets.ACTIONS_DOCUMENTATION_TOKEN }}

jobs:
  Automatic-Documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
      - name: Install Pdoc
        run: pip install pdoc
      - name: Setup pre-commit
        run : |
          pip install pre-commit
          pre-commit install
      - name: Install aws_cdk
        run: python -m pip install -r requirements.txt
      - name: Delete old documentation files
        run: rm -rf documentation/
      - name: Generate documentation with pdoc
        run:  pdoc s3_website/ -o ${GITHUB_WORKSPACE}/documentation
      - name: Set-Up Git Name and Email, Add, Commit and Push
        run: |
          echo ACTIONS_TOKEN
          git config --global user.name "Automatic Documentation Generator"
          git config --global user.email "autodoc@autodoc.com"
          git add documentation/
          git commit -m "documentation generated via github actions" --no-verify
      - name: si
        if:  TOKEN == ACTIONS_TOKEN
        run: echo "siuuuuuuuuuuuu"